export const TRAILS = [
    {
        id: 0,
        name: "Mount Rose Summit",
        summary: "8-mile out-and-back hike to the summit of Mount Rose. A must for everyone who lives in the area. Plan for a full day.",
        distanceAndDifficulty: "8 miles. Strenuous uphill and high altitude makes it seem longer. 6+ hours round trip.",
        sunExposure: "Mix of shade throughout. Full sun at summit.",
        traffic: "Heavy. Lots of tourists on warm days.",
        bikes: "Not recommended.",
        seasons: "Early fall. Crowded in summer and easy to get sunburn at the summit. Late spring is OK, but it is often cold in early spring.",
        directions: "https://www.google.com/maps/dir//Mt.+Rose+Summit+Tahoe+Rim+Trail+Trailhead/@39.3167674,-119.9090143,14.14z/data=!4m5!3m4!1s0x80996e6272b82601:0x809d9eab873c67b5!8m2!3d39.3131999!4d-119.8973823",
        center: {
            lat: 39.316089,
            lng: -119.904114
          },
        zoom: 10.5,
        parkingEntrance: "Big parking that gets full on a busy holiday. Bathrooms at the base. Only one trail entrance -- can't miss it.",
        additionalInfo: "",
        longDescription: "<p>The hike to Mount Rose Summit is an important rite of passage for anyone who lives in Reno or Tahoe. It's a full day trip, so pack accordingly. Along the way, you will meet lots of other travelers, many from out of the area. It's not for those seeking solitude, but it is one of the best views in the area.</p><p>Begin at the parking lot, perched at the highest point of Mount Rose highway, a few miles past Mount Rose ski resot if you are coming from Reno. The parking lot has a trail that starts uphill labeled the Tahoe Rim Trail; make sure to take this one and not the Tamarack Lake Trail farther down. For the first few miles, enjoy a gradual climb to the waterfall, which is the first main stopping point where many travelers take pictures.</p><p>At this point, you will continue onto the Rim-to-Rose trail. From here to the peak, the uphill slope will increase, and you will pass through many forested sections before you reach the peack, which is fully exposed. Watch out for altitude sickness as you get higher up.</p><p>Spend some time at the top to take pictures of the surrounding areas and resting from the grueling last stretch. This is one of the best views in the Sierras and certainly the best in Northern Nevada. Walk back the same way you came, taking relief in the fact that it is entirely downhill.</p>",
        photoRoll1: "/assets/images/mtrose2.jpg",
        photoLabel1: "The last ascent",
        photoRoll2: "/assets/images/mtrose1.jpg",
        photoLabel2: "View near the top",
        photoRoll3: "/assets/images/mtrose3.jpg",
        photoLabel3: "View from the top",
        photoRoll4: "/assets/images/mtrose4.jpg",
        photoLabel4: "View of the gorgeous meadow"
    },
    {   
        id: 1,
        name: "Whites Creek to Dry Pond",
        summary: "8-mile hike to the summit of Mount Rose. A must for everyone who lives in the area. Plan for a full day.",
        distanceAndDifficulty: "8 miles. Strenuous uphill and high altitude makes it seem longer. 6+ hours round trip.",
        sunExposure: "Mix of shade throughout. Full sun at summit.",
        traffic: "Heavy. Lots of tourists on warm days.",
        bikes: "Not recommended.",
        seasons: "Early fall. Crowded in summer and easy to get sunburn at the summit. Late spring is OK, but it is often cold in early spring.",
        directions: "https://www.google.com/maps/dir//Whites+Creek+Dry+Pond+Trailhead/@39.3781439,-119.850806,16.23z/data=!4m5!3m4!1s0x80996b9092541689:0x335cbc2353832828!8m2!3d39.3780709!4d-119.8480524",
        center: {
            lat: 39.377925,
            lng: -119.847967
          },
        zoom: 10.5,
        parkingEntrance: "Big parking that gets full on a busy holiday. Bathrooms at the base. Only one trail entrance -- can't miss it.",
        additionalInfo: "",
        longDescription: "",
        photoRoll1: "",
        photoLabel1: "",
        photoRoll2: "",
        photoLabel2: "",
        photoRoll3: "",
        photoLabel3: "",
        photoRoll4: "",
        photoLabel4: ""
    },
    {   
        id: 2,
        name: "Thomas Creek to Mt. Rose Wilderness",
        summary: "8-mile hike to the summit of Mount Rose. A must for everyone who lives in the area. Plan for a full day.",
        distanceAndDifficulty: "8 miles. Strenuous uphill and high altitude makes it seem longer. 6+ hours round trip.",
        sunExposure: "Mix of shade throughout. Full sun at summit.",
        traffic: "Heavy. Lots of tourists on warm days.",
        bikes: "Not recommended.",
        seasons: "Early fall. Crowded in summer and easy to get sunburn at the summit. Late spring is OK, but it is often cold in early spring.",
        directions: "https://www.google.com/maps/dir//Whites+Creek+Dry+Pond+Trailhead/@39.3781439,-119.850806,16.23z/data=!4m5!3m4!1s0x80996b9092541689:0x335cbc2353832828!8m2!3d39.3780709!4d-119.8480524",
        center: {
            lat: 39.377925,
            lng: -119.847967
          },
        zoom: 10.5,
        parkingEntrance: "Big parking that gets full on a busy holiday. Bathrooms at the base. Only one trail entrance -- can't miss it.",
        additionalInfo: "",
        longDescription: "",
        photoRoll1: "",
        photoLabel1: "",
        photoRoll2: "",
        photoLabel2: "",
        photoRoll3: "",
        photoLabel3: "",
        photoRoll4: "",
        photoLabel4: ""
    },
];