export const TRAILS = [
    {
        id: 0,
        name: "Mount Rose Summit",
        image: "/assets/images/hikeMountRose.jpg",
        summary: "8-mile hike to the summit of Mount Rose. A must for everyone who lives in the area. Plan for a full day.",
        distanceAndDifficulty: "8 miles. Strenuous uphill and high altitude makes it seem longer. 6+ hours round trip.",
        sunExposure: "Mix of shade throughout. Full sun at summit.",
        traffic: "Heavy. Lots of tourists on warm days.",
        bikes: "Not recommended.",
        seasons: "Early fall. Crowded in summer and easy to get sunburn at the summit. Late spring is OK, but it is often cold in early spring.",
        directions: "https://www.google.com/maps/dir//Mt.+Rose+Summit+Tahoe+Rim+Trail+Trailhead/@39.3167674,-119.9090143,14.14z/data=!4m5!3m4!1s0x80996e6272b82601:0x809d9eab873c67b5!8m2!3d39.3131999!4d-119.8973823",
        lat: "",
        long: "",
        parkingEntrance: "Big parking that gets full on a busy holiday. Bathrooms at the base. Only one trail entrance -- can't miss it.",
        additionalInfo: "",
        longDescription: "<p>The hike to Mount Rose Summit is an important rite of passage for anyone who lives in Reno or Tahoe.</p><p>It's a full day trip, so pack accordingly. Along the way, you will meet lots of other travelers, many from out of the area. It's not for those seeking solitude, but it is one of the best views in the area.</p>",
        photoRoll1: "/assets/images/mtrose2.jpg",
        photoRoll2: "/assets/images/mtrose1.jpg",
        photoRoll3: "/assets/images/mtrose3.jpg",
        photoRoll4: "/assets/images/mtrose4.jpg"
    },
    {
        id: 1,
        name: "Whites Creek to Dry Pond",
        image: "/assets/images/hikeMountRose.jpg",
        summary: "8-mile hike to the summit of Mount Rose. A must for everyone who lives in the area. Plan for a full day.",
        distanceAndDifficulty: "8 miles. Strenuous uphill and high altitude makes it seem longer. 6+ hours round trip.",
        sunExposure: "Mix of shade throughout. Full sun at summit.",
        traffic: "Heavy. Lots of tourists on warm days.",
        bikes: "Not recommended.",
        seasons: "Early fall. Crowded in summer and easy to get sunburn at the summit. Late spring is OK, but it is often cold in early spring.",
        directions: "https://www.google.com/maps/dir//Whites+Creek+Dry+Pond+Trailhead/@39.3781439,-119.850806,16.23z/data=!4m5!3m4!1s0x80996b9092541689:0x335cbc2353832828!8m2!3d39.3780709!4d-119.8480524",
        lat: "",
        long: "",
        parkingEntrance: "Big parking that gets full on a busy holiday. Bathrooms at the base. Only one trail entrance -- can't miss it.",
        additionalInfo: "",
        longDescription: "",
        photoRoll1: "",
        photoRoll2: "",
        photoRoll3: "",
        photoRoll4: ""
    }
];